config/routes.rb
Rails.application.routes.draw do
  
  

  resources :ad_formats

  resources :articles

  resources :sections

  resources :magazines do
    resources :ads
  end  

 root 'application#hello'

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :magazine
  
  def ad_formats=(array)
    self[:ad_formats]=(array.compact.join(", "))
  end
  
  def ad_formats 
    self[:ad_formats].split(", ")
  end
  
  def has_format?(string)
    if self.ad_formats.include?(string)
      return true
    end
  end 
 
end

app/models/ad_format.rb
class AdFormat < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :section
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  has_many :ads, :dependent => :destroy
  has_many :sections
  has_many :articles, through: :sections
  accepts_nested_attributes_for :ads
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :magazine
  has_many :articles
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
before_action :set_ad, only: [:show, :edit, :update, :destroy]
# GET /ads
# GET /ads.json
def index
@magazine = Magazine.find_by_id(params[:magazine_id])
@ads = @magazine.ads
end
# GET /ads/1
# GET /ads/1.json
def show
@magazine = Magazine.find_by_id(params[:magazine_id])
@ads = @magazine.ads.find(params[:id])
end
# GET /ads/new
def new
@magazine = Magazine.find_by_id(params[:magazine_id])
@ad = @magazine.ads.build
end
# GET /ads/1/edit
def edit
@magazine = Magazine.find_by_id(params[:magazine_id])
@ads = @magazine.ads.find(params[:id])
end
# POST /ads
# POST /ads.json
def create
@magazine = Magazine.find_by_id(params[:magazine_id])
@ad = @magazine.ads.build(ad_params)
respond_to do |format|
if @ad.save
format.html { redirect_to magazine_ad_path(@magazine, @ad), notice:
'Ad was successfully updated.' }
format.json { render :show, status: :created, location: @ad }
else
format.html { render :new }
format.json { render json: @ad.errors, status: :unprocessable_entity }
end
end
end
# PATCH/PUT /ads/1
# PATCH/PUT /ads/1.json
def update
@magazine = Magazine.find_by_id(params[:magazine_id])
respond_to do |format|
if @ad.update(ad_params)
format.html { redirect_to magazine_ad_path(@magazine, @ad), notice:
'Ad was successfully updated.' }
format.json { render :show, status: :ok, location: @ad }
else
format.html { render :edit }
format.json { render json: @ad.errors, status: :unprocessable_entity }
end
end
end
# DELETE /ads/1
# DELETE /ads/1.json
def destroy
@magazine = Magazine.find_by_id(params[:magazine_id])
@ad.destroy
respond_to do |format|
format.html { redirect_to magazine_ads_path(@magazine), notice: 'Ad was successfully destroyed.' }
format.json { head :no_content }
end
end
private
# Use callbacks to share common setup or constraints between actions.
def set_ad
@ad = Ad.find(params[:id])
end
# Never trust parameters from the scary internet, only allow the white list through.
def ad_params
#params.require(:magazine).permit(ad: [:vendor, :copy]) error: param is missing or #the #value is empty: magazine; Parameters:
#{"utf8"=>"✓",
# "authenticity_token"=>"LcQ4WupX2owiqlCwwXpa4Ezk/pgubrWjRNgkyQqWF0M=",
# "ad"=>{"vendor"=>"SampleVendor",
# "copy"=>"SampleCopy"},
# "commit"=>"Create Ad",
# "magazine_id"=>"1"}
#params.require(:magazine).permit!
#same error
  #debug
  params.require(:ad).permit(:magazine_id, :vendor, :copy, :ad_formats => [])
  #params.require(:ad).permit!
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.
# For APIs, you may want to use :null_session instead.
protect_from_forgery with: :exception
def hello
render text: "Hello, world!"
end
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
before_action :set_magazine, only: [:show, :edit, :update, :destroy]
# GET /magazines
# GET /magazines.json
def index
@magazines = Magazine.all
end
# GET /magazines/1
# GET /magazines/1.json
def show
end
# GET /magazines/new
def new
@magazine = Magazine.new
end
# GET /magazines/1/edit
def edit
end
# POST /magazines
# POST /magazines.json
def create
@magazine = Magazine.new(magazine_params)
respond_to do |format|
if @magazine.save
format.html { redirect_to @magazine, notice: 'Magazine was successfully created.' }
format.json { render :show, status: :created, location: @magazine }
else
format.html { render :new }
format.json { render json: @magazine.errors, status: :unprocessable_entity }
end
end
end
# PATCH/PUT /magazines/1
# PATCH/PUT /magazines/1.json
def update
respond_to do |format|
if @magazine.update(magazine_params)
format.html { redirect_to @magazine, notice: 'Magazine was successfully updated.' }
format.json { render :show, status: :ok, location: @magazine }
else
format.html { render :edit }
format.json { render json: @magazine.errors, status: :unprocessable_entity }
end
end
end
# DELETE /magazines/1
# DELETE /magazines/1.json
def destroy
@magazine.destroy
respond_to do |format|
format.html { redirect_to magazines_url, notice: 'Magazine was successfully destroyed.' }
format.json { head :no_content }
end
end
private
# Use callbacks to share common setup or constraints between actions.
def set_magazine
@magazine = Magazine.find(params[:id])
end
# Never trust parameters from the scary internet, only allow the white list through.
def magazine_params
params.require(:magazine).permit(:name)
end
end

app/helpers/ad_formats_helper.rb
module AdFormatsHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/ad_formats/_form.html.erb
<%= form_for(@ad_format) do |f| %>
  <% if @ad_format.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad_format.errors.count, "error") %> prohibited this ad_format from being saved:</h2>

      <ul>
      <% @ad_format.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ad_formats/edit.html.erb
<h1>Editing ad_format</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad_format %> |
<%= link_to 'Back', ad_formats_path %>

app/views/ad_formats/index.html.erb
<h1>Listing ad_formats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ad_formats.each do |ad_format| %>
      <tr>
        <td><%= ad_format.name %></td>
        <td><%= link_to 'Show', ad_format %></td>
        <td><%= link_to 'Edit', edit_ad_format_path(ad_format) %></td>
        <td><%= link_to 'Destroy', ad_format, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ad format', new_ad_format_path %>

app/views/ad_formats/new.html.erb
<h1>New ad_format</h1>

<%= render 'form' %>

<%= link_to 'Back', ad_formats_path %>

app/views/ad_formats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ad_format.name %>
</p>

<%= link_to 'Edit', edit_ad_format_path(@ad_format) %> |
<%= link_to 'Back', ad_formats_path %>

app/views/ads/_form.html.erb
<%= form_for([@magazine, @ad]) do |f| %>
  <%= hidden_field_tag "ad[ad_formats][]", "" %>
  <% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% @ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vendor %><br>
    <%= f.text_field :vendor %>
  </div>
  <div class="field">
    <%= f.label :copy %><br>
    <%= f.text_field :copy %>
  </div>
 
  <strong>Ad Formats:</strong>
    <p>
    <% AdFormat.all.each do |format| %>
      <div>
        <%= check_box_tag "ad[ad_formats][]", format.name, @ad.has_format?(format.name) %>
        <%= format.name %>
      </div>
      <% end %>
    </p>

    
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ads/edit.html.erb
<h1>Editing ad</h1>

<%= render 'form' %>

<%= link_to 'Show', magazine_ad_path(@magazine, @ad) %> |
<%= link_to 'Back', magazine_ads_path(@magazine) %>

app/views/ads/index.html.erb
<h1>Listing ads</h1>

<table>
  <thead>
    <tr>
      <th>Magazine</th>
      <th>Vendor</th>
      <th>Copy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ads.each do |ad| %>
      <tr>
        <td><%= ad.magazine_id %></td>
        <td><%= ad.vendor %></td>
        <td><%= ad.copy %></td>
        <td><%= link_to 'Show', magazine_ad_path(@magazine, ad) %></td>
        <td><%= link_to 'Edit', edit_magazine_ad_path(@magazine, ad) %></td>
        <td><%= link_to 'Destroy', magazine_ad_path(@magazine, ad), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ad', new_magazine_ad_path(@magazine) %>

app/views/ads/new.html.erb
<h1>New ad</h1>

<%= render 'form' %>


<%= link_to 'Back', magazine_ads_path %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Magazine:</strong>
  <%= @ad.magazine_id %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @ad.vendor %>
</p>

<p>
  <strong>Copy:</strong>
  <%= @ad.copy %>
</p>

<p>
  <strong>Ad Format:</strong>
  <% @ad.ad_formats.each do |format| %>
    <%= format %>
  <% end %>
</p>

<%= link_to 'Edit', edit_magazine_ad_path(@magazine, @ad) %> |
<%= link_to 'Back', magazine_ads_path(@magazine) %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :section_id %><br>
    <%= f.number_field :section_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= article.section_id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Section:</strong>
  <%= @article.section_id %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/magazines/_form.html.erb
<%= form_for(@magazine) do |f| %>
  <% if @magazine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@magazine.errors.count, "error") %> prohibited this magazine from being saved:</h2>

      <ul>
      <% @magazine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/magazines/edit.html.erb
<h1>Editing magazine</h1>

<%= render 'form' %>

<%= link_to 'Show', @magazine %> |
<%= link_to 'Back', magazines_path %>

app/views/magazines/index.html.erb
<h1>Listing magazines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @magazines.each do |magazine| %>
      <tr>
        <td><%= magazine.name %></td>
        <td><%= link_to 'Show', magazine %></td>
        <td><%= link_to 'Edit', edit_magazine_path(magazine) %></td>
        <td><%= link_to 'Destroy', magazine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Magazine', new_magazine_path %>

app/views/magazines/new.html.erb
<h1>New magazine</h1>

<%= render 'form' %>

<%= link_to 'Back', magazines_path %>

app/views/magazines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @magazine.name %>
</p>

<%= link_to 'Edit', edit_magazine_path(@magazine) %> |
<%= link_to 'Back', magazines_path %>

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :magazine_id %><br>
    <%= f.number_field :magazine_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<h1>Listing sections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Magazine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.title %></td>
        <td><%= section.magazine_id %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New section</h1>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>

<p>
  <strong>Magazine:</strong>
  <%= @section.magazine_id %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>